search_agent:
  results_per_query: 5
  max_results_for_summary: 25
  serpapi_params:
    gl: "us"
    hl: "en"
    tbm: "nws"  # news
    tbs: "qdr:d"  # last 24 hours
  llm:
    model: "gpt-4.1"
    model_provider: "openai"
    temperature: 0.3
  summary_prompt: |
    Create a concise summary of trending topics from these search results for "{query}".
    
    Include:
    - Key trending topics
    - Recent developments
    - New releases
    
    Keep it factual and brief.
    
    Search Results:
    {content_text}
    
    Summary:
  system_message: "You are a technical analyst who creates factual summaries of news and industry developments. Your summaries help identify trending topics and patterns that are useful for content scoring and trend analysis. Focus on objective facts, recent developments, and industry movements rather than subjective opinions."
  queries:
  - AI Agents
  - LangChain OR LangGraph
  - Anthropic OR OpenAI
  - LLM
  - CrewAI OR AutoGen
