name: Tests

# Trigger workflow on pull requests and pushes to main branch
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Get the source code from the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Install Python 3.13 (latest stable version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Cache pip dependencies to speed up subsequent runs
      # Cache key changes when requirements.txt changes
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-
            ${{ runner.os }}-pip-

      # Install project dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the test suite with pytest
      # --maxfail=1: Stop after first failure for faster feedback
      # --disable-warnings: Hide warnings for cleaner output
      # -q: Quiet mode for concise output
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
